### ISSUE TITLE
Need to re-install to see bounding tile update

### ISSUE THREAD

**Issue by codeadsa** [EvanesceExotica/Journal-To-Canvas-Slideshow#11]
I noticed that you updated the module via readme.md, but didn't assign a new version number? So Foundry doesn't detect an update. I had to uninstall and re-install to see your bounding tile updates. Tested bounding tile and it worked out great. Thanks for this valued update!

**Comment by EvanesceExotica** [comment]
No problem! I'm glad you're enjoying it, and the bounding tile implementation is all thanks to @Occidio ^ ^

Thanks for your concern! So I haven't actually officially updated the module just yet, I just merged the pull requests from @Occidio and @p4535992. On my side of things, I'm working on a rewrite and update to the merged script to allow things like using bounding tiles + display tiles in separate scenes (aside from the Display Scene), and I intend to update the module with these features officially (with a new version number) in the next couple of days -- hopefully by tomorrow.

So Foundry shouldn't alert that there's an update just yet ^ ^

**Comment by EvanesceExotica** [comment]
This should be fixed in update v0.1.4  ^ ^ It's been officially updated now.
