### ISSUE TITLE
Feature request: show NPC/PC images

### ISSUE THREAD

**Issue by DarKDinDoN** [EvanesceExotica/Journal-To-Canvas-Slideshow#13]
Hello,

Great update you did on the module! Congrats!

There is one missing set of images to display for this module, and these are the actor images!
Without it, we have to copy over the image from the actor portrait to a journal entry in order to display it. Kind of duplicating it.

Next step I suggest is to make is so these portraits can be displayed to the players directly from the actor sheet!

**Comment by EvanesceExotica** [comment]
Thank you so much! And great suggestion! -- I'll certainly give that a go for my next update.

**Comment by EvanesceExotica** [comment]
So this should now work in v0.1.5 when you turn on the "Use Actor Sheet Images" option in the module settings. You can now right click a character portrait on an actor sheet to display it. Lemme know if you have any trouble with it!
