### ISSUE TITLE
Cleaning up the interface

### ISSUE THREAD

**Issue by DarKDinDoN** [EvanesceExotica/Journal-To-Canvas-Slideshow#14]
Hi,

With so many modules out there, one could have a lot of them installed and activated.
A lot of these modules add buttons & icons in the FVTT interface. Resulting in an over crowed interface.

Would you mind making sure, only the required buttons are displayed?
Meaning, depending on the "Display Location" setting and "Display Windows Behavior", can you only show the relevant buttons.

My understanding of the module:
- "Display scene" ▶️ Only the "Create or show display scene", "Clear display", "Create bouding tile", "Create display tile" and "set url images" buttons
- "Any scene" ▶️ same as "Display scene"
- "Window" + "Dedicated journal entry" ▶️ only "Create of show display entry",  "Clear display" and "set url images" buttons
- "Window" + "New window" ▶️ only the "set url images" buttons*

Thx

**Comment by EvanesceExotica** [comment]
Sure! That's a very good idea, thanks! I'll work on that for the next update. :)
