### ISSUE TITLE
Images in journal don't highlight and are not clickable

### ISSUE THREAD

**Issue by TheChaosmeister** [EvanesceExotica/Journal-To-Canvas-Slideshow#17]
Hello,

I am running Foundry 0.7.9 and the latest version of JTCS. I started a fresh blank 5e world. Activated the module. it is the only Module. Added the Display scene. Its the only scene and active. Created the Display Journal. It is the only Journal Entry. Added an Image within the text editor as well as an Image in the image mode of the Display Journal. Hovering over them with the mouse does not highlight them, I can't click on them. I tried to look with F12 but cant see anything. I am in the Foundry Program.

**Comment by TheChaosmeister** [comment]
Solved it, misread instruction, my deepest apologies.

**Comment by EvanesceExotica** [comment]
No worries!
