### ISSUE TITLE
Feature Request - Avoid when you click on the image of the journal to activate the "Display" scene by default

### ISSUE THREAD

**Issue by p4535992** [EvanesceExotica/Journal-To-Canvas-Slideshow#2]
**Environment Details**

Foundry VTT Version: 0.7.9

Operating System: [Linux]

How Are You Using Foundry: [Linux,Native Application (Electron), Chrome]

Which Game System: Dungeons and Dragons 5th Edition, version 1.2.0

Modules Enabled?: yes

OS, Hosting, Browser (if applicable): Linux/Node/Chrome

**Description Details**

When i'm on a differente scene than "Display" if i click on the journal image the module automatically activate the "Display" scene with the image clicked. But for example i just want to check out a image during a combat i don't want to activate a new scene.

I can think at two solutions:

1) It will be better if the module is active only when the current activated scene is "Display", because only when i show that scene make sense the "storytelling".

2) Just avoid to activate by default the "Display" scene when i click on the image on a journal.

**Comment by EvanesceExotica** [comment]
Hey there! 
I just released version 0.1.1 -- in it I turned off the functionality to activate the scene after clicking on an image in the journal. So all clicking on a journal image does now it does is change the tile in the Display scene without switching to it. 

So instead you can either manually activate the Display scene or click the button at the bottom of the Scenes tab to activate it. 

Hope that helps!

**Comment by p4535992** [comment]
Wow, ty. Super fast.
