### ISSUE TITLE
Feature request: crossfade

### ISSUE THREAD

**Issue by modzy2** [EvanesceExotica/Journal-To-Canvas-Slideshow#26]
It would be awesome to be able to set an optional crossfade time value to have it fade out any previous image at the same time as fading in the new image.

**Comment by EvanesceExotica** [comment]
Hey, there!
I wanted to mention that I don't think this feature is currently possible
with the way Journal to Canvas Slideshow works. I imagine it could be done
with some more research and an overhaul of the code on my part, but
unfortunately with my current school workload, I don't currently have the
time :(

So instead, I'd like to suggest a few other modules that might have
features like this, or might more likely have them in the future. ^ ^

The first is ShareMedia by DarkDinDon, which is an awesome newer module
that was based off of this one. The author of that one did a lot of amazing
work on this one too, and I highly recommend it. :)
https://github.com/DarKDinDoN/share-media

Another is Monk's Enhanced Journal by Iron Monk, which has a Slideshow
feature that might include crossfading capabilities.
https://github.com/ironmonk88/monks-enhanced-journal

I hope that helps, and apologies for the letdown :(

**Comment by modzy2** [comment]
No worries and thanks for the tips
