### ISSUE TITLE
Module broken in v9

### ISSUE THREAD

**Issue by JulieWinchester** [EvanesceExotica/Journal-To-Canvas-Slideshow#30]
I know the module isn't described as compatible with v9! :) Thanks for creating it, it's been very useful for me in my game, so I wanted to document what seems to be happening in Foundry v9. 

Can set up display scene just fine, but on clicking an image in a journal entry to show in the display scene, nothing happens. This error results: 

<img width="832" alt="Screen Shot 2022-01-08 at 6 06 50 PM" src="https://user-images.githubusercontent.com/14943160/148664135-10241b2c-0ffe-42ca-b7fe-d35744b7a39f.png">

I'm guessing this has to do with entity deprecation and the use of `app.entity` the `renderJournalSheet` hook (pictured below), but I don't know enough about Foundry module development to really say.

<img width="578" alt="Screen Shot 2022-01-08 at 6 09 02 PM" src="https://user-images.githubusercontent.com/14943160/148664202-2a26071d-c5f3-49d7-aa04-6c509baf11af.png">

**Comment by EvanesceExotica** [comment]
Hey there! I do intend to update this for v9 when I have some time; should
be a quick fix from what I can see ^ ^
Thanks so much for documenting where things are going wrong -- that's a big
help!
