### ISSUE TITLE
v11 compatibility

### ISSUE THREAD

**Issue by dsakura** [EvanesceExotica/Journal-To-Canvas-Slideshow#50]
Hello, 
do you intend to update the project or did you stop with it? It's one of the best I use, it helps the theater of the mind a lot.
Thank you very much

**Comment by gsterling** [comment]
At first glance it looks compatible.

If you want to use it, just open up the `module.json` and change `maximum` in the `compatibility`-section from 10 to 11 and reload foundry. You should now be able to activate it. It does work exactly as I set it up in V10.

**Comment by dsakura** [comment]
Nice, I'll test. Many thanks
