### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by marcosmachado81** [EvanesceExotica/Journal-To-Canvas-Slideshow#7]
FoundryVTT 0.7.9
Savage Worlds Adventure Edition 0.17.1
Journal To Canvas Slideshow 0.1.3

I created the journal "Display" and the screen Display but the images inside the journal aren't clickable (Display Location Window or Scene).

Automatically Show Display is checked

**Comment by codeadsa** [comment]
Try deleting the Display Scene, and re-create a new one. Sometimes this occurs for me.

**Comment by EvanesceExotica** [comment]
Hey there! Apologies for the late reply; I've been swamped with school work lately :(

If what codeadsa suggested doesn't work, could you try a couple of things for me?

1. If possible, try the module out in a fresh world with no other modules installed (either that or you can disable the modules in the world you're currently using, but the fresh world might be less of a hassle)

2. If that doesn't work, if possible, try the module in a fresh world with a different game system. The one I'm using currently with my games is the Cypher System, so I know for a fact it should work with that one. 

This way we can figure out if it's a conflict with another module, or the game system (Savage Worlds Adventure Edition is what you're using?), that's causing the issue. And if not, we can rule those out. 

I've had other users have similar issues using certain systems or other modules that affect or reformat the way journal entries display, and I can probably find a way to hack around it if that is what's happening.

**Comment by marcosmachado81** [comment]
Hello!
I don't know how.. When I logged out, cleared the browser cache the module starts working :)

a very useful and must-have module

Thank you very much :)
