### ISSUE TITLE
Please limit the image to the max size of the orig. tile

### ISSUE THREAD

**Issue by codeadsa** [EvanesceExotica/Journal-To-Canvas-Slideshow#9]
Right now it seems that no matter how small a size the orig. tile is on the Display Scene, when you present an image from the journal, it scales to the size of the scene. If possible, can you limit the scale to the max size of the tile dimension. This way the image is bound to the area defined by the tile, and won't exceed the area.

**Comment by EvanesceExotica** [comment]
Sure thing! Right now, the display tile basically scales depending on the size of the scene itself, the size of the image's texture, and a hard-coded value in my code. I was working on adding a way to change how much the tile is scaled by in the settings.  

 @Occidio made some awesome additions that I merged into my code today that allows you to create another tile that acts as a sort of 'bounding box' for the display tile, so the tile will scale only to be as large as that "bounding tile" (and centered on it as well).

That should be included soon once I make some extra changes and updates and then officially publish the next version of the module. 

Thanks so much for your patience :)

**Comment by codeadsa** [comment]
Thanks great work from you and contributors.

**Comment by EvanesceExotica** [comment]
Alright, so this issue should be resolved in version v0.1.4 with the addition of the bounding tiles ^ ^
